"""add role field to user

Revision ID: d70c2330ae6a
Revises: 66c015882eb2
Create Date: 2026-09-26 11:28:47.161824

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d70c2330ae6a"
down_revision: str | Sequence[str] | None = "66c015882eb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
