"""Add senha_hash to users

Revision ID: 66c015882eb2
Revises: ec293423f6f0
Create Date: 2026-09-25 15:23:07.093985

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66c015882eb2"
down_revision: str | Sequence[str] | None = "ec293423f6f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("senha_hash", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("senha_hash", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "senha_hash")
    op.drop_column("admins", "senha_hash")
    # ### end Alembic commands ###
