"""Initial PG migration

Revision ID: ec293423f6f0
Revises:
Create Date: 2026-09-25 15:13:00.498804

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec293423f6f0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("SUPER_ADMIN", "ADMIN", "VIEWER", name="roleadmin"), nullable=False
        ),
        sa.Column("oauth_provider", sa.String(length=50), nullable=False),
        sa.Column("oauth_sub", sa.String(length=255), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "bssid_allowlist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bssid", sa.String(length=17), nullable=False),
        sa.Column("ssid_associado", sa.String(length=255), nullable=True),
        sa.Column("descricao", sa.String(length=255), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ip_allowlist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ip_cidr", sa.String(length=50), nullable=False),
        sa.Column("descricao", sa.String(length=255), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("tipo", sa.Enum("ALUNO", "STAFF", name="tipousuario"), nullable=False),
        sa.Column("turma_ou_equipe", sa.String(length=100), nullable=False),
        sa.Column("oauth_provider", sa.String(length=50), nullable=False),
        sa.Column("oauth_sub", sa.String(length=255), nullable=False),
        sa.Column("patrimonio", sa.String(length=100), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("admin_aprovado", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_users_tipo", "users", ["tipo"], unique=False)
    op.create_index("ix_users_turma_ou_equipe", "users", ["turma_ou_equipe"], unique=False)
    op.create_table(
        "config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chave", sa.String(length=100), nullable=False),
        sa.Column("valor", sa.Text(), nullable=False),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("atualizado_por", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["atualizado_por"], ["admins.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chave"),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("mac_address", sa.String(length=17), nullable=False),
        sa.Column("serial_number", sa.String(length=255), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("os_type", sa.String(length=50), nullable=False),
        sa.Column("principal", sa.Boolean(), nullable=False),
        sa.Column(
            "registrado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mac_address"),
    )
    op.create_table(
        "checkins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("hora_checkin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_publico", sa.String(length=45), nullable=True),
        sa.Column("ssid", sa.String(length=255), nullable=True),
        sa.Column("bssids", sa.JSON(), nullable=True),
        sa.Column("status", sa.Enum("PRESENTE", "ATRASADO", name="statuscheckin"), nullable=False),
        sa.Column("turno_referencia", sa.String(length=50), nullable=False),
        sa.Column("exportado_sheets", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "turno_referencia", name="uq_checkin_user_turno"),
    )
    op.create_index("ix_checkins_criado_em", "checkins", ["criado_em"], unique=False)
    op.create_index(
        "ix_checkins_user_turno", "checkins", ["user_id", "turno_referencia"], unique=False
    )
    op.create_table(
        "checkin_duplicatas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("checkin_original_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("hora_tentativa", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_publico", sa.String(length=45), nullable=True),
        sa.Column("motivo", sa.String(length=100), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["checkin_original_id"], ["checkins.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("checkin_duplicatas")
    op.drop_index("ix_checkins_user_turno", table_name="checkins")
    op.drop_index("ix_checkins_criado_em", table_name="checkins")
    op.drop_table("checkins")
    op.drop_table("devices")
    op.drop_table("config")
    op.drop_index("ix_users_turma_ou_equipe", table_name="users")
    op.drop_index("ix_users_tipo", table_name="users")
    op.drop_table("users")
    op.drop_table("ip_allowlist")
    op.drop_table("bssid_allowlist")
    op.drop_table("admins")
    # ### end Alembic commands ###
