"""add role field really

Revision ID: a02dab1dca18
Revises: d70c2330ae6a
Create Date: 2026-09-26 11:32:17.720604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02dab1dca18'
down_revision: Union[str, Sequence[str], None] = 'd70c2330ae6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'VIEWER', 'NONE', name='roleadmin'), server_default='NONE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
